import { GoogleTagManager } from "@next/third-parties/google";

import { Abel, Montserrat } from "next/font/google";
import "./globals.css";

import "@fortawesome/fontawesome-svg-core/styles.css";

const abel = Abel({
  subsets: ["latin"],
  variable: "--font-abel",
  weight: "400",
});
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: "400",
});

export const metadata = {
  title: "La Company Creativa",
  description: "Generated by create next app",
};

export default function RootLayout({ children, ...props }) {
  return (
    <html lang="en" className={`${abel.variable} ${montserrat.variable}`}>
      <body>{children}</body>
      <GoogleTagManager gtmId="GTM-WJ345W3" />
    </html>
  );
}
